interface - help
helpCust
	"prints help intro to Transcript"

	Transcript show: '  Customers:';cr.
	Transcript show: '     Add  -  addCustWithFirst:Last:';cr.
	Transcript show: '     View  -  viewCust:';cr.
	Transcript show: '     View all  -  viewAll';cr.
	Transcript show: '     Update first name  -  updateCust:WithFirst:';cr.
	Transcript show: '     Update last name  -  updateCust:WithLast:';cr.
	Transcript show: '     Delete  -  deleteCust:';cr.
	
